export { default as Landing } from './Landing/Landing';
export { default as ErrorPage } from './ErrorPage/ErrorPage';
export { default as Navbar } from './Navbar/Navbar';
export { default as Hero } from './Hero/Hero';
export { default as Skills } from './Skills/Skills';
export { default as Projects } from './Projects/Projects';
export { default as SpartanSocial } from './Projects/SpartanSocial';
export { default as MockUni } from './Projects/MockUni';
export { default as PairingTool } from './Projects/PairingTool';